@echo off

set COMMON_COMPILER_FLAGS=/c /nologo /EHa- /GR- /fp:fast /Oi /W4 /Fm /std:c++17
set DEBUG_FLAGS=/DDEBUG_BUILD /Od /MTd /Zi
set PREPROCESSOR_DEFINITIONS=/DUNICODE /DNOMINMAX
set RELEASE_FLAGS=/O2
set COMPILER_FLAGS=%COMMON_COMPILER_FLAGS% %DEBUG_FLAGS% %PREPROCESSOR_DEFINITIONS%
REM set COMPILER_FLAGS=%COMMON_COMPILER_FLAGS% %RELEASE_FLAGS%
set LINKER_FLAGS=/INCREMENTAL:NO /opt:ref
set SYSTEM_LIBS=
set SRC=kwindow.cpp
cl %COMPILER_FLAGS% %SRC% /link %LINKER_FLAGS% %SYSTEM_LIBS%
lib /OUT:kwindow.lib kwindow.obj
echo Done
